name: Create build branches

on:
  workflow_dispatch:

env:
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  create_branches:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Create and switch to branch build/dynamic-demo
        run: |
          git checkout -b build/dynamic-demo

      - name: Modify src/index.tsx by replacing import lines
        run: |
          sed -i 's|import.*@dynamic-framework/ui-react/dist/css/dynamic-ui.css.*|if (process.env.NODE_ENV === "development") {\n  require("@dynamic-framework/ui-react/dist/css/dynamic-ui.css");\n}|' src/index.tsx
          
          sed -i 's|import.*./styles/base.scss.*|require("./styles/base.scss");|' src/index.tsx
          
          git config user.email "github-actions@github.com"
          git config user.name "GitHub Actions"
          git add src/index.tsx
          git commit -m "chore: setup conditional style import to deploy to dynamic"
          git push origin build/dynamic-demo

      - name: Create branch build/dynamic-catalog from build/dynamic-demo
        run: |
          git checkout -b build/dynamic-catalog build/dynamic-demo
          git push origin build/dynamic-catalog
