name: Release Please

on:
  push:
    branches:
      - master

permissions:
  contents: write
  pull-requests: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: googleapis/release-please-action@v4
        with:
          target-branch: master
          # This token requires a Personal Access Token (PAT) with the `repo` scope enabled.
          # The `repo` scope is necessary for the action to have sufficient permissions
          # to create pull requests in the repository.
          token: ${{ secrets.RELEASE_PLEASE_TOKEN }}
          config-file: release-please-config.json
          manifest-file: release-please-manifest.json